pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = 'brutalabhi'
        IMAGE_NAME = 'magic-url-app'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    options {
        timestamps()
        ansiColor('xterm')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker image') {
            steps {
                script {
                    dir('MagicURL') {
                        bat "docker build -t ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} ."
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    dir('MagicURL') {
                        // Check if container starts legally
                        bat """
                        docker run --rm -d --name magicurl-test ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
                        ping -n 5 127.0.0.1 > nul
                        docker ps | findstr magicurl-test
                        docker rm -f magicurl-test
                        """
                    }
                }
            }
        }

        stage('Push image') {
            steps {
                script {
                    // This block will fail if the ID in Jenkins Credentials doesn't match 'docker-registry-creds'
                    withCredentials([usernamePassword(credentialsId: 'docker-registry-creds', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                        bat "docker login -u %DOCKER_USER% -p %DOCKER_PASS%"
                        bat "docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
                    }
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                script {
                    sshagent (credentials: ['ec2-ssh-creds']) {
                        bat """
                        ssh -o StrictHostKeyChecking=no ubuntu@13.60.167.75 "docker pull ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}; docker rm -f magicurl-app || true; docker run -d --name magicurl-app -p 80:3000 --restart unless-stopped -e MONGO_URI='mongodb://mongo:27017/magicurl' ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}

